### PR TITLE
Add option to dump bee mutation to a CSV file

### PR DESCRIPTION
**Pull request by traydent**
Process is based on the potions dump from NEI (https://github.com/Chicken-Bones/NotEnoughItems/blob/d59b28f8fcce1b55af02e3429b522b6062f08643/src/codechicken/nei/api/ItemInfo.java#L179).

It dumps all the mutations found in CSV format into the dumps folder.

### CODE REVIEW

**Comment by bdew** [comment]
This looks interesting but i'm going to rewrite it to be cleaner and support other (tree/flower/etc.) mutations.

**Comment by fcharton** [comment]
It was a first try at minecraft mod hacking, and I was willing to know if the feature was «acceptable». Might I still try to improve this patch ?

**Comment by traydent** [comment]
It was a first try at minecraft mod hacking, and I was willing to know if the feature was «acceptable». Might I still try to improve this patch ?

**Comment by bdew** [comment]
Sorry, already done :P

I didn't meant to shoot down your work, it just needed some minor tweaking (like localization stuff, working with other mutation types, etc.)

Oh yeah and i rewrote it in Scala because at some point i'll be rewriting all of NEI addons anyway.

**Pull request closed without merging**
