### PR TITLE
Update mod dependency info for Forestry 4

### PR DESCRIPTION
**Pull request by mezz**
NEIAddons built for Forestry 4.0.8 will [crash](http://pastebin.com/1RrSx6pw) with earlier Forestry versions, so I'd like to add version dependency info.

### CODE REVIEW

**Comment by bdew** [comment]
Does it actually crash on anything?

The version check should be updated [here](https://github.com/bdew/neiaddons/blob/mc1710/src/net/bdew/neiaddons/forestry/AddonForestry.java#L51) which i guess i forgot to do for a while :P

That will (unlike forge version bounds) cause the module just not to load instead of causing an error when loaded with older forestry.

Also it doesn't need "required-after:NotEnoughItems" - it can be loaded on servers without NEI to provide some functionality - that's a rare but supported use case.

**Comment by mezz** [comment]
Ok, makes sense. I did get this crash report: http://pastebin.com/1RrSx6pw
The signature for a couple things changed to be more specific, like `IAlleleBeeSpecies` instead of `IAlleleSpecies`. It doesn't require migration effort but it is a breaking change.

**Comment by bdew** [comment]
Ok i updated the version number and verified that it works with both old versions (by disabling the plugin as it should) and the new ones.

**Comment by mezz** [comment]
Thanks!

**Pull request closed without merging**
