### PR TITLE
Create it_IT.lang + localized some Nei subsets

### PR DESCRIPTION
**Pull request by TheVikingWarrior**

### CODE REVIEW

**Comment by labpaw** [comment]
Where did you found Fluids and Fluid Containers? With NEI addons installed I can't find them...

**Comment by TheVikingWarrior** [comment]
Hm, might be Nei plugins... I'll remove them form here

**Comment by labpaw** [comment]
Maybe you let me add subsets localization for en_US.lang and for ru_RU.lang in one commit? And you can add just it_IT.lang localization in one commit by another PR. Because 5 commits for just localization is just too much :D

**Comment by TheVikingWarrior** [comment]
Ok

**Comment by bdew** [comment]
I've reformated the commits for proper attribution and less mess :P

**Pull request closed without merging**
